### PR TITLE
Adding caption data-part

### PR DESCRIPTION
**Pull request by navels**

### CODE REVIEW

**Comment by kyeotic** [comment]
Can you also add a `text` binding for it. I imagine that will fill the general case.

**Comment by navels** [comment]
Not sure that will play well with formatting.  For example, I want to do this:

```
<caption data-part="caption" class="text-left"><h3>My Table</h3></caption>
```

But I guess one can still do that, it'll just override the bound text.  Maybe that's okay.

**Comment by kyeotic** [comment]
Node's with bindings _and_ data-parts do not keep their bindings when being overridden. That's actually why overriding the grid body requires you to bind the `foreach: rows` yourself.

**Comment by kyeotic** [comment]
Btw, you said you were new to git so just in case you didn't know: if you just update the files in your branch the pull request will be updated automatically.

For future reference, you don't even need the separate branch on your fork. You can just make the changes in master, since your fork is its own independent repository. (This doesn't make any difference to me, it just might save you a couple seconds )

**Comment by navels** [comment]
Done, thanks for the tips!

**Comment by kyeotic** [comment]
Thank Navels, looks good =)

**Pull request merged**
